### ISSUE TITLE
Random crashes in PCPSendUnsolicitedAnnounce()

### ISSUE THREAD

**Issue by jonitis** [miniupnp/miniupnp#327]
(gdb) bt
#0  memcpy (dest=0x7f8138b4, src=<optimized out>, n=16) at src/string/memcpy.c:27
#1  0x0040f8e5 in copyIPv6IfDifferent.lto_priv.42 ()
#2  0x0040da83 in createPCPResponse.lto_priv.39 ()
#3  0x0040af2f in PCPSendUnsolicitedAnnounce ()
#4  0x0040335d in main ()

Problem is in fact that createPCPResponse() assumes that response argument always receives data from request and for second byte does not set opcode, but just sets most significant bit:

response[1] |= 0x80;	/* r_opcode */

Then it checks for opcode match and it depends on the garbage in the uninitialized buff array.
Instead of passing info.opcode = PCP_OPCODE_ANNOUNCE when opcode is not really used by createPCPResponse() the initial value of request opcode must be set.

Patch:
diff --git a/pcpserver.c b/pcpserver.c
index f262ede..735033c 100644
--- a/pcpserver.c
+++ b/pcpserver.c
@@ -1434,7 +1434,7 @@ static int processPCPRequest(void * req, int req_size, pcp_info_t *pcp_msg_info)
 }
 
 
-static void createPCPResponse(unsigned char *response, pcp_info_t *pcp_msg_info)
+static void createPCPResponse(unsigned char *response, const pcp_info_t *pcp_msg_info)
 {
        response[2] = 0;        /* reserved */
        memset(response + 12, 0, 12);   /* reserved */
@@ -1652,8 +1652,8 @@ void PCPSendUnsolicitedAnnounce(int * sockets, int n_sockets)
 #endif /* ENABLE_IPV6 */
        /* this is an Unsolicited ANNOUNCE response */
 
+       buff[1] = PCP_OPCODE_ANNOUNCE;
        info.version = this_server_info.server_version;
-       info.opcode = PCP_OPCODE_ANNOUNCE;
        info.result_code = PCP_SUCCESS;
        info.lifetime = 0;
        createPCPResponse(buff, &info);

**Comment by jonitis** [comment]
This is new issue in v2.1:
https://github.com/miniupnp/miniupnp/commit/7492fe42c280b57d9579db4f3a2a34366874f743#diff-c0e42c5d38910741125f5a5235ed648c
